import { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: 'beef', name: 'Beef', nameAr: 'لحم البقر', image: '/images/categories/beef.jpg', description: 'Premium cuts from grain-fed cattle' },
  { id: 'lamb', name: 'Lamb', nameAr: 'لحم الضأن', image: '/images/categories/lamb.jpg', description: 'Tender farm-fresh lamb' },
  { id: 'chicken', name: 'Chicken', nameAr: 'دجاج', image: '/images/categories/chicken.jpg', description: 'Free-range halal chicken' },
  { id: 'goat', name: 'Mutton', nameAr: 'لحم الماعز', image: '/images/categories/goat.jpg', description: 'Fresh local goat meat' },
//  { id: 'wagyu', name: 'Wagyu', nameAr: 'لحم واغيو', image: '/images/categories/wagyu.jpg', description: 'Japanese A5 Wagyu beef' },
  //{ id: 'seafood', name: 'Seafood', nameAr: 'مأكولات بحرية', image: '/images/categories/seafood.jpg', description: 'Fresh daily catch' },
  //{ id: 'bbq', name: 'BBQ Specials', nameAr: 'تشكيلة الشواء', image: '/images/categories/bbq.jpg', description: 'Ready-to-grill selections' },
  //{ id: 'family', name: 'Family Packs', nameAr: 'عروض العائلة', image: '/images/categories/family.jpg', description: 'Value packs for the whole family' },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Premium Ribeye Steak',
    nameAr: 'ستيك ريبي الفاخر',
    description: 'Hand-selected, grain-fed ribeye steak with exceptional marbling. Perfect for grilling or pan-searing.',
    category: 'beef',
    price: 89,
    originalPrice: 110,
    stock: 50,
    weightOptions: [
      { label: '500g', weight: 500, price: 89 },
      { label: '1kg', weight: 1000, price: 169 },
      { label: '2kg', weight: 2000, price: 320 },
    ],
    images: [
      'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=600',
      'https://images.unsplash.com/photo-1558030006-450675393462?w=600',
    ],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 128,
    nutritionInfo: { calories: 271, protein: 26, fat: 18, carbs: 0, per100g: true },
    origin: 'Australia',
    tags: ['premium', 'grilling', 'bestseller'],
    createdAt: new Date(),
  },
  {
    id: 'p2',
    name: 'Wagyu A5 Tenderloin',
    nameAr: 'فيليه واغيو A5',
    description: 'Ultra-premium Japanese Wagyu A5 grade tenderloin. The pinnacle of beef luxury with extraordinary marbling.',
    category: 'wagyu',
    price: 299,
    stock: 15,
    weightOptions: [
      { label: '300g', weight: 300, price: 299 },
      { label: '500g', weight: 500, price: 449 },
      { label: '1kg', weight: 1000, price: 850 },
    ],
    images: [
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600',
    ],
    featured: true,
    isNew: true,
    rating: 5.0,
    reviewCount: 45,
    nutritionInfo: { calories: 332, protein: 24, fat: 26, carbs: 0, per100g: true },
    origin: 'Japan',
    tags: ['wagyu', 'luxury', 'premium'],
    createdAt: new Date(),
  },
  {
    id: 'p3',
    name: 'Lamb Rack (French Cut)',
    nameAr: 'ضلع الضأن فرنسي',
    description: 'Frenched rack of lamb from premium New Zealand farms. Elegant and perfect for special occasions.',
    category: 'lamb',
    price: 145,
    stock: 30,
    weightOptions: [
      { label: '700g', weight: 700, price: 145 },
      { label: '1.4kg', weight: 1400, price: 275 },
    ],
    images: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=600',
      'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=600',
    ],
    featured: true,
    isNew: false,
    rating: 4.8,
    reviewCount: 89,
    nutritionInfo: { calories: 258, protein: 25, fat: 17, carbs: 0, per100g: true },
    origin: 'New Zealand',
    tags: ['lamb', 'premium', 'special occasion'],
    createdAt: new Date(),
  },
  {
    id: 'p4',
    name: 'Whole Organic Chicken',
    nameAr: 'دجاجة عضوية كاملة',
    description: 'Free-range, halal-certified organic chicken raised without antibiotics. Rich flavor, tender meat.',
    category: 'chicken',
    price: 38,
    stock: 100,
    weightOptions: [
      { label: '1kg', weight: 1000, price: 38 },
      { label: '1.5kg', weight: 1500, price: 52 },
      { label: '2kg', weight: 2000, price: 68 },
    ],
    images: [
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600',
    ],
    featured: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 212,
    nutritionInfo: { calories: 165, protein: 31, fat: 4, carbs: 0, per100g: true },
    origin: 'UAE',
    tags: ['organic', 'halal', 'chicken'],
    createdAt: new Date(),
  },
  {
    id: 'p5',
    name: 'Beef Tenderloin',
    nameAr: 'فيليه بقر',
    description: 'The most tender cut of beef, lean and luxuriously soft. Perfect for special occasions.',
    category: 'beef',
    price: 125,
    stock: 40,
    weightOptions: [
      { label: '500g', weight: 500, price: 125 },
      { label: '1kg', weight: 1000, price: 235 },
    ],
    images: [
      'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600',
    ],
    featured: true,
    isNew: false,
    rating: 4.9,
    reviewCount: 76,
    nutritionInfo: { calories: 212, protein: 28, fat: 11, carbs: 0, per100g: true },
    origin: 'Brazil',
    tags: ['beef', 'tender', 'premium'],
    createdAt: new Date(),
  },
  {
    id: 'p6',
    name: 'BBQ Family Feast Pack',
    nameAr: 'باكج الشواء العائلي',
    description: 'Complete BBQ pack with mixed grills: kofta, lamb chops, chicken wings, and marinated beef skewers.',
    category: 'bbq',
    price: 185,
    originalPrice: 220,
    stock: 25,
    weightOptions: [
      { label: '2kg', weight: 2000, price: 185 },
      { label: '4kg', weight: 4000, price: 350 },
    ],
    images: [
      'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600',
    ],
    featured: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 54,
    origin: 'UAE',
    tags: ['bbq', 'family', 'value'],
    createdAt: new Date(),
  },
  {
    id: 'p7',
    name: 'Fresh King Prawns',
    nameAr: 'روبيان ملكي طازج',
    description: 'Jumbo king prawns sourced daily from Oman. Perfect for grilling, stir-fry, or curries.',
    category: 'seafood',
    price: 95,
    stock: 20,
    weightOptions: [
      { label: '500g', weight: 500, price: 95 },
      { label: '1kg', weight: 1000, price: 180 },
    ],
    images: [
      'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600',
    ],
    featured: false,
    isNew: true,
    rating: 4.6,
    reviewCount: 38,
    origin: 'Oman',
    tags: ['seafood', 'prawns', 'fresh'],
    createdAt: new Date(),
  },
  {
    id: 'p8',
    name: 'Lamb Shoulder (Bone-In)',
    nameAr: 'كتف ضأن بالعظم',
    description: 'Whole bone-in lamb shoulder, perfect for slow roasting or traditional Emirati harees and ouzi dishes.',
    category: 'lamb',
    price: 78,
    stock: 35,
    weightOptions: [
      { label: '1kg', weight: 1000, price: 78 },
      { label: '2kg', weight: 2000, price: 148 },
      { label: '3kg', weight: 3000, price: 210 },
    ],
    images: [
      'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600',
    ],
    featured: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 93,
    origin: 'Australia',
    tags: ['lamb', 'slow cook', 'traditional'],
    createdAt: new Date(),
  },
];

export const reviews = [
  {
    id: 'r1',
    userName: 'Ahmed Al Mansouri',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    rating: 5,
    comment: 'Exceptional quality! The Wagyu was absolutely divine. Delivery was on time and packaging was premium.',
    city: 'Dubai',
  },
  {
    id: 'r2',
    userName: 'Fatima Al Zaabi',
    userAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b050?w=100',
    rating: 5,
    comment: 'Best meat delivery in UAE! The ribeye steak was perfectly marbled. Will definitely order again.',
    city: 'Abu Dhabi',
  },
  {
    id: 'r3',
    userName: 'Mohammed Hassan',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    rating: 5,
    comment: 'The BBQ family pack was a hit at our gathering. Fresh, halal, and delivered cold. Highly recommend!',
    city: 'Sharjah',
  },
  {
    id: 'r4',
    userName: 'Sara Al Rashidi',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    rating: 5,
    comment: 'Ordered the lamb rack for a dinner party and everyone was impressed. Premium quality at fair prices.',
    city: 'Ajman',
  },
];

export const uaeCities = [
  { name: 'Dubai', lat: 25.2048, lng: 55.2708, available: true },
  { name: 'Abu Dhabi', lat: 24.4539, lng: 54.3773, available: true },
  { name: 'Sharjah', lat: 25.3463, lng: 55.4209, available: true },
  { name: 'Ajman', lat: 25.4052, lng: 55.5136, available: true },
  { name: 'Ras Al Khaimah', lat: 25.7889, lng: 55.9760, available: true },
  { name: 'Fujairah', lat: 25.1288, lng: 56.3265, available: true },
  { name: 'Umm Al Quwain', lat: 25.5647, lng: 55.5533, available: true },
];
